variable "vpc_cidr" {}
variable "availability_zones" {}
variable "project_name" {}
variable "env" {}
variable "region" {}
variable "instance_type" {}
variable "ecs_task_desired_count" {}
variable "ecs_task_deployment_minimum_healthy_percent" {}
variable "ecs_task_deployment_maximum_percent" {}
variable "container_name" {}
variable "container_port" {}
variable "ecs_task_cpu" {}
variable "memory" {}
variable "log_retention_in_days" {}
variable "ecs_task_max_count" {}
variable "ecs_task_min_count" {}
variable "cap_minimum_scaling_step_size" {}
variable "cap_maximum_scaling_step_size" {}
variable "cap_target_capacity" {}
variable "cpu_target_tracking_desired_value" {}
variable "memory_target_tracking_desired_value" {}
variable "autoscaling_min_size" {}
variable "autoscaling_max_size" {}
