name: Terraform Infrastructure Pipeline

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Deployment Environment"
        required: true
        default: "prod"
        type: choice
        options:
          - stage
          - prod

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      ENVIRONMENT: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Add Credentials to AWS Profile
        run: |
          mkdir -p ~/.aws
          echo "[av-sandbox]" >> ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "region=${{ env.AWS_REGION }}" >> ~/.aws/credentials

      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure/terraform/environments/${{ env.ENVIRONMENT }}
        
      - name: Terraform Validate
        run: terraform validate
        working-directory: infrastructure/terraform/environments/${{ env.ENVIRONMENT }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: infrastructure/terraform/environments/${{ env.ENVIRONMENT }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: infrastructure/terraform/environments/${{ env.ENVIRONMENT }}
